/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
	T extends ColumnType<infer S, infer I, infer U>
		? ColumnType<S, I | undefined, U>
		: ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
	[x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AssetCategories {
	archived_at: Timestamp | null;
	created_at: Generated<Timestamp>;
	id: Generated<string>;
	kind: string;
	label_i18n: Json | null;
	label_key: string | null;
	lifespan_years: number | null;
	maintenance_pct: Numeric | null;
	residual_pct: Numeric | null;
	sort_order: Generated<number>;
	tenant_id: string;
}

export interface Assets {
	brand: string | null;
	category_id: string;
	created_at: Generated<Timestamp>;
	description: string | null;
	id: Generated<string>;
	insured_value_cents: Int8 | null;
	insured_value_year: number | null;
	lifespan_years: number | null;
	model: string | null;
	owner_membership_id: string | null;
	ownership: Generated<string>;
	purchase_price_cents: Int8 | null;
	purchase_year: number | null;
	serial_number: string | null;
	status: Generated<string>;
	tag: string | null;
	tenant_id: string;
	updated_at: Generated<Timestamp>;
}

export interface Assignments {
	asset_id: string;
	checked_out_at: Generated<Timestamp>;
	condition_in: string | null;
	condition_out: string | null;
	id: Generated<string>;
	issued_by_membership_id: string | null;
	location_id: string | null;
	membership_id: string | null;
	notes: string | null;
	returned_at: Timestamp | null;
	returned_by_membership_id: string | null;
	tenant_id: string;
}

export interface AuditLog {
	action: string;
	actor_membership_id: string | null;
	at: Generated<Timestamp>;
	changed_fields: Generated<Json>;
	id: Generated<Int8>;
	request_id: string | null;
	subject_id: string | null;
	subject_type: string;
	tenant_id: string;
}

export interface AuthTokens {
	consumed_at: Timestamp | null;
	created_at: Generated<Timestamp>;
	expires_at: Timestamp;
	issued_by: string | null;
	issued_in_tenant_id: string | null;
	membership_id: string | null;
	purpose: string;
	target_tenant_id: string | null;
	token_hash: Buffer;
	user_id: string | null;
}

export interface Locations {
	archived_at: Timestamp | null;
	created_at: Generated<Timestamp>;
	id: Generated<string>;
	name: string;
	tenant_id: string;
}

export interface MembershipRoles {
	membership_id: string;
	role_id: string;
	tenant_id: string;
}

export interface Permissions {
	code: string;
	group_key: string;
	is_dangerous: Generated<boolean>;
}

export interface PlatformAuditLog {
	action: string;
	actor_user_id: string | null;
	at: Generated<Timestamp>;
	changed_fields: Generated<Json>;
	id: Generated<Int8>;
	request_id: string | null;
	subject_id: string | null;
	subject_type: string;
}

export interface RateLimits {
	hits: number;
	key: string;
	window_start: Timestamp;
}

export interface RolePermissions {
	permission_code: string;
	role_id: string;
	tenant_id: string;
}

export interface Roles {
	created_at: Generated<Timestamp>;
	id: Generated<string>;
	is_system: Generated<boolean>;
	label_i18n: Json | null;
	label_key: string | null;
	tenant_id: string;
	updated_at: Generated<Timestamp>;
	version: Generated<number>;
}

export interface Sessions {
	created_at: Generated<Timestamp>;
	expires_at: Timestamp;
	last_seen_at: Generated<Timestamp>;
	scoped_tenant_id: string | null;
	token_hash: Buffer;
	user_id: string;
}

export interface TenantMemberships {
	anonymized_at: Timestamp | null;
	created_at: Generated<Timestamp>;
	display_name: string | null;
	email: string | null;
	id: Generated<string>;
	member_number: string | null;
	notes: string | null;
	phone: string | null;
	pseudonym_id: string | null;
	status: Generated<string>;
	tenant_id: string;
	updated_at: Generated<Timestamp>;
	user_id: string | null;
}

export interface Tenants {
	created_at: Generated<Timestamp>;
	currency: Generated<string>;
	default_locale: Generated<string>;
	fiscal_year_start_month: Generated<number>;
	id: Generated<string>;
	name: string;
	slug: string;
	status: Generated<string>;
	updated_at: Generated<Timestamp>;
}

export interface ThemeSettings {
	color_accent: string | null;
	color_primary: Generated<string>;
	color_secondary: Generated<string>;
	density: Generated<string>;
	font_family: Generated<string>;
	logo_object_key: string | null;
	radius: Generated<string>;
	tenant_id: string;
	updated_at: Generated<Timestamp>;
	version: Generated<number>;
}

export interface Users {
	created_at: Generated<Timestamp>;
	credential_scope_tenant_id: string | null;
	email: string;
	email_verified_at: Timestamp | null;
	erased_at: Timestamp | null;
	id: Generated<string>;
	last_tenant_id: string | null;
	password_hash: string | null;
	platform_role: string | null;
	preferred_locale: string | null;
	updated_at: Generated<Timestamp>;
}

export interface DB {
	asset_categories: AssetCategories;
	assets: Assets;
	assignments: Assignments;
	audit_log: AuditLog;
	auth_tokens: AuthTokens;
	locations: Locations;
	membership_roles: MembershipRoles;
	permissions: Permissions;
	platform_audit_log: PlatformAuditLog;
	rate_limits: RateLimits;
	role_permissions: RolePermissions;
	roles: Roles;
	sessions: Sessions;
	tenant_memberships: TenantMemberships;
	tenants: Tenants;
	theme_settings: ThemeSettings;
	users: Users;
}
